# Header
menu:
  首頁: /
  經典內容: /collection
  本服優勢: /service
  文章分享: /blog
  關於本站: /contact

# Blog
blog_title: 文章分享
blog_subtitle: 分享中文攻略

# Blog pagination
# path: Root path for your blogs index page. (default = '/blog')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
blog_generator:
  per_page: 6
  path: /blog
  order_by: -date

# Miscellaneous
favicon: /images/icon.ico
